import { FormEvent, useState } from "react";
import { LogIn, Music2, UserPlus } from "lucide-react";
import { continueAsGuest, loginAccount, registerAccount } from "../shared/api/client";

type Props = { onAuthenticated: () => void };

export function AuthPage({ onAuthenticated }: Props) {
  const [mode, setMode] = useState<"login" | "register">("login");
  const [login, setLogin] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent) { e.preventDefault(); setError(""); setBusy(true); try { if (mode === "login") await loginAccount(login, password); else await registerAccount(login, email, password); onAuthenticated(); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось выполнить вход"); } finally { setBusy(false); } }
  async function guest() { setError(""); setBusy(true); try { await continueAsGuest(); onAuthenticated(); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось открыть гостевой режим"); } finally { setBusy(false); } }
  return <main className="min-h-screen grid place-items-center bg-[#090b14] px-5 text-white"><section className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.04] p-7 shadow-2xl"><div className="mb-7 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-fuchsia-500/20 text-fuchsia-300"><Music2 /></span><div><h1 className="text-2xl font-bold">Cryon</h1><p className="text-sm text-white/55">Музыка в одном месте</p></div></div><h2 className="text-xl font-semibold">{mode === "login" ? "Вход в приложение" : "Создание аккаунта"}</h2><p className="mt-2 text-sm text-white/55">Учётная запись хранится только на этом компьютере.</p><form className="mt-6 space-y-4" onSubmit={submit}>{mode === "register" && <input aria-label="Email" value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Электронная почта" required className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-fuchsia-400"/>}<input aria-label="Логин" value={login} onChange={e=>setLogin(e.target.value)} placeholder="Логин" minLength={3} required className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-fuchsia-400"/><input aria-label="Пароль" value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Пароль (минимум 8 символов)" minLength={8} required className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-fuchsia-400"/>{error && <p role="alert" className="text-sm text-rose-300">{error}</p>}<button disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-fuchsia-500 px-4 py-3 font-semibold disabled:opacity-50">{mode === "login" ? <LogIn size={18}/> : <UserPlus size={18}/>}{busy ? "Подождите…" : mode === "login" ? "Войти" : "Создать аккаунт"}</button></form><button disabled={busy} onClick={guest} className="mt-3 w-full rounded-xl border border-white/10 px-4 py-3 text-sm text-white/75 hover:bg-white/5">Продолжить как гость</button><button onClick={()=>{setMode(mode === "login" ? "register" : "login");setError("")}} className="mt-5 w-full text-sm text-fuchsia-300">{mode === "login" ? "Нет аккаунта? Создать" : "Уже есть аккаунт? Войти"}</button></section></main>;
}