// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {http} from '../models';
import {store} from '../models';
import {audiofetcher} from '../models';
import {lyrics} from '../models';
import {core} from '../models';
import {playback} from '../models';
import {context} from '../models';
import {fs} from '../models';

export function AddFavorite(arg1:domain.Track):Promise<void>;

export function AddHistory(arg1:domain.Track):Promise<void>;

export function AddLocalFolder(arg1:string):Promise<Array<domain.Track>>;

export function AddNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTrackToPlaylist(arg1:string,arg2:domain.Track):Promise<void>;

export function AssetHandler():Promise<http.Handler>;

export function ClearHistory():Promise<void>;

export function ClearNotifications():Promise<void>;

export function ContinueAsGuest():Promise<store.Account>;

export function CreatePlaylist(arg1:string,arg2:string):Promise<domain.UserPlaylist>;

export function CurrentAccount():Promise<store.Account>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function GetAlbumTracks(arg1:string,arg2:string):Promise<Array<domain.Track>>;

export function GetArtist(arg1:string):Promise<domain.ArtistInfo>;

export function GetAudioStream(arg1:string,arg2:string):Promise<audiofetcher.AudioStream>;

export function GetLocalCover(arg1:string):Promise<string>;

export function GetLyrics(arg1:string,arg2:string,arg3:string,arg4:number):Promise<lyrics.Result>;

export function GetSetting(arg1:string):Promise<string>;

export function ImportFavorites(arg1:string):Promise<core.FavoritesImportResult>;

export function ImportSpotifyLibraryExport(arg1:string):Promise<core.FavoritesImportResult>;

export function LastFMConnected():Promise<boolean>;

export function ListAccountConnections():Promise<Array<core.AccountConnectionStatus>>;

export function ListAutoMix(arg1:string,arg2:number):Promise<Array<domain.Track>>;

export function ListDailyMix(arg1:number):Promise<Array<domain.Track>>;

export function ListFavorites():Promise<Array<domain.Track>>;

export function ListHistory():Promise<Array<core.HistoryItem>>;

export function ListLocalFolders():Promise<Array<string>>;

export function ListLocalTracks():Promise<Array<domain.Track>>;

export function ListNewReleases(arg1:number):Promise<Array<domain.Track>>;

export function ListNotifications():Promise<Array<store.NotificationRow>>;

export function ListPlaylistTracks(arg1:string):Promise<Array<domain.Track>>;

export function ListPlaylists():Promise<Array<domain.UserPlaylist>>;

export function ListRecommendations(arg1:number):Promise<Array<domain.Track>>;

export function ListRelatedTracks(arg1:domain.Track,arg2:number):Promise<Array<domain.Track>>;

export function ListSourceStatus():Promise<Array<core.SourceStatus>>;

export function ListSources():Promise<Array<string>>;

export function ListWeeklyDiscoveries(arg1:number):Promise<Array<domain.Track>>;

export function LoginAccount(arg1:string,arg2:string):Promise<store.Account>;

export function LogoutAccount():Promise<void>;

export function MarkAllNotificationsRead():Promise<void>;

export function PickMusicFolder():Promise<string>;

export function PickSpotifyLibraryExport():Promise<string>;

export function PlayerBackendAvailable():Promise<boolean>;

export function PlayerPause():Promise<void>;

export function PlayerPlay(arg1:string,arg2:string):Promise<void>;

export function PlayerResume():Promise<void>;

export function PlayerSeek(arg1:number):Promise<void>;

export function PlayerSetEqualizer(arg1:Array<number>):Promise<void>;

export function PlayerSetNormalize(arg1:boolean):Promise<void>;

export function PlayerSetVolume(arg1:number):Promise<void>;

export function PlayerStatus():Promise<playback.Status>;

export function PlayerStop():Promise<void>;

export function RecoFeedbackState():Promise<Record<string, number>>;

export function RecommendationsAvailable():Promise<boolean>;

export function RegisterAccount(arg1:string,arg2:string,arg3:string):Promise<store.Account>;

export function RemoveFavorite(arg1:string,arg2:string):Promise<void>;

export function RemoveLocalFolder(arg1:string):Promise<Array<domain.Track>>;

export function RemoveNotification(arg1:string):Promise<void>;

export function RemoveTrackFromPlaylist(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderPlaylistTracks(arg1:string,arg2:Array<store.PlaylistTrackKey>):Promise<void>;

export function RescanLocalLibrary():Promise<Array<domain.Track>>;

export function ResetAllData():Promise<void>;

export function ResolveAlbum(arg1:string,arg2:string):Promise<Array<domain.Track>>;

export function ResolvePlayableTrack(arg1:domain.Track):Promise<domain.Track>;

export function Search(arg1:string,arg2:string):Promise<Array<domain.Track>>;

export function SearchAll(arg1:string):Promise<Array<domain.Track>>;

export function SearchInSources(arg1:string,arg2:Array<string>):Promise<Array<domain.Track>>;

export function SetLastFMKey(arg1:string):Promise<void>;

export function SetOAuthApplicationConfig(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetRecoFeedback(arg1:string,arg2:string,arg3:number):Promise<Record<string, number>>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function SetSoundCloudClientID(arg1:string):Promise<void>;

export function SetSpotifyCredentials(arg1:string,arg2:string):Promise<void>;

export function SetYandexToken(arg1:string):Promise<void>;

export function SetYouTubeAPIKey(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function SoundCloudClientIDSet():Promise<boolean>;

export function SpotifyConnected():Promise<boolean>;

export function StartMobileServer(arg1:fs.FS):Promise<string>;

export function StartSpotifyLogin():Promise<void>;

export function StartYandexLogin():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdatePlaylist(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UseWailsRuntime():Promise<void>;

export function ValidateSource(arg1:string):Promise<void>;

export function YandexTokenConnected():Promise<boolean>;

export function YouTubeAPIKeySet():Promise<boolean>;
