// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1) {
  return window['go']['main']['App']['AddFavorite'](arg1);
}

export function AddHistory(arg1) {
  return window['go']['main']['App']['AddHistory'](arg1);
}

export function AddLocalFolder(arg1) {
  return window['go']['main']['App']['AddLocalFolder'](arg1);
}

export function AddNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddNotification'](arg1, arg2, arg3);
}

export function AddTrackToPlaylist(arg1, arg2) {
  return window['go']['main']['App']['AddTrackToPlaylist'](arg1, arg2);
}

export function AssetHandler() {
  return window['go']['main']['App']['AssetHandler']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ClearNotifications() {
  return window['go']['main']['App']['ClearNotifications']();
}

export function ContinueAsGuest() {
  return window['go']['main']['App']['ContinueAsGuest']();
}

export function CreatePlaylist(arg1, arg2) {
  return window['go']['main']['App']['CreatePlaylist'](arg1, arg2);
}

export function CurrentAccount() {
  return window['go']['main']['App']['CurrentAccount']();
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function GetAlbumTracks(arg1, arg2) {
  return window['go']['main']['App']['GetAlbumTracks'](arg1, arg2);
}

export function GetArtist(arg1) {
  return window['go']['main']['App']['GetArtist'](arg1);
}

export function GetAudioStream(arg1, arg2) {
  return window['go']['main']['App']['GetAudioStream'](arg1, arg2);
}

export function GetLocalCover(arg1) {
  return window['go']['main']['App']['GetLocalCover'](arg1);
}

export function GetLyrics(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetLyrics'](arg1, arg2, arg3, arg4);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function ImportFavorites(arg1) {
  return window['go']['main']['App']['ImportFavorites'](arg1);
}

export function ImportSpotifyLibraryExport(arg1) {
  return window['go']['main']['App']['ImportSpotifyLibraryExport'](arg1);
}

export function LastFMConnected() {
  return window['go']['main']['App']['LastFMConnected']();
}

export function ListAccountConnections() {
  return window['go']['main']['App']['ListAccountConnections']();
}

export function ListAutoMix(arg1, arg2) {
  return window['go']['main']['App']['ListAutoMix'](arg1, arg2);
}

export function ListDailyMix(arg1) {
  return window['go']['main']['App']['ListDailyMix'](arg1);
}

export function ListFavorites() {
  return window['go']['main']['App']['ListFavorites']();
}

export function ListHistory() {
  return window['go']['main']['App']['ListHistory']();
}

export function ListLocalFolders() {
  return window['go']['main']['App']['ListLocalFolders']();
}

export function ListLocalTracks() {
  return window['go']['main']['App']['ListLocalTracks']();
}

export function ListNewReleases(arg1) {
  return window['go']['main']['App']['ListNewReleases'](arg1);
}

export function ListNotifications() {
  return window['go']['main']['App']['ListNotifications']();
}

export function ListPlaylistTracks(arg1) {
  return window['go']['main']['App']['ListPlaylistTracks'](arg1);
}

export function ListPlaylists() {
  return window['go']['main']['App']['ListPlaylists']();
}

export function ListRecommendations(arg1) {
  return window['go']['main']['App']['ListRecommendations'](arg1);
}

export function ListRelatedTracks(arg1, arg2) {
  return window['go']['main']['App']['ListRelatedTracks'](arg1, arg2);
}

export function ListSourceStatus() {
  return window['go']['main']['App']['ListSourceStatus']();
}

export function ListSources() {
  return window['go']['main']['App']['ListSources']();
}

export function ListWeeklyDiscoveries(arg1) {
  return window['go']['main']['App']['ListWeeklyDiscoveries'](arg1);
}

export function LoginAccount(arg1, arg2) {
  return window['go']['main']['App']['LoginAccount'](arg1, arg2);
}

export function LogoutAccount() {
  return window['go']['main']['App']['LogoutAccount']();
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function PickMusicFolder() {
  return window['go']['main']['App']['PickMusicFolder']();
}

export function PickSpotifyLibraryExport() {
  return window['go']['main']['App']['PickSpotifyLibraryExport']();
}

export function PlayerBackendAvailable() {
  return window['go']['main']['App']['PlayerBackendAvailable']();
}

export function PlayerPause() {
  return window['go']['main']['App']['PlayerPause']();
}

export function PlayerPlay(arg1, arg2) {
  return window['go']['main']['App']['PlayerPlay'](arg1, arg2);
}

export function PlayerResume() {
  return window['go']['main']['App']['PlayerResume']();
}

export function PlayerSeek(arg1) {
  return window['go']['main']['App']['PlayerSeek'](arg1);
}

export function PlayerSetEqualizer(arg1) {
  return window['go']['main']['App']['PlayerSetEqualizer'](arg1);
}

export function PlayerSetNormalize(arg1) {
  return window['go']['main']['App']['PlayerSetNormalize'](arg1);
}

export function PlayerSetVolume(arg1) {
  return window['go']['main']['App']['PlayerSetVolume'](arg1);
}

export function PlayerStatus() {
  return window['go']['main']['App']['PlayerStatus']();
}

export function PlayerStop() {
  return window['go']['main']['App']['PlayerStop']();
}

export function RecoFeedbackState() {
  return window['go']['main']['App']['RecoFeedbackState']();
}

export function RecommendationsAvailable() {
  return window['go']['main']['App']['RecommendationsAvailable']();
}

export function RegisterAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterAccount'](arg1, arg2, arg3);
}

export function RemoveFavorite(arg1, arg2) {
  return window['go']['main']['App']['RemoveFavorite'](arg1, arg2);
}

export function RemoveLocalFolder(arg1) {
  return window['go']['main']['App']['RemoveLocalFolder'](arg1);
}

export function RemoveNotification(arg1) {
  return window['go']['main']['App']['RemoveNotification'](arg1);
}

export function RemoveTrackFromPlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveTrackFromPlaylist'](arg1, arg2, arg3);
}

export function ReorderPlaylistTracks(arg1, arg2) {
  return window['go']['main']['App']['ReorderPlaylistTracks'](arg1, arg2);
}

export function RescanLocalLibrary() {
  return window['go']['main']['App']['RescanLocalLibrary']();
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function ResolveAlbum(arg1, arg2) {
  return window['go']['main']['App']['ResolveAlbum'](arg1, arg2);
}

export function ResolvePlayableTrack(arg1) {
  return window['go']['main']['App']['ResolvePlayableTrack'](arg1);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SearchAll(arg1) {
  return window['go']['main']['App']['SearchAll'](arg1);
}

export function SearchInSources(arg1, arg2) {
  return window['go']['main']['App']['SearchInSources'](arg1, arg2);
}

export function SetLastFMKey(arg1) {
  return window['go']['main']['App']['SetLastFMKey'](arg1);
}

export function SetOAuthApplicationConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetOAuthApplicationConfig'](arg1, arg2, arg3);
}

export function SetRecoFeedback(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetRecoFeedback'](arg1, arg2, arg3);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function SetSoundCloudClientID(arg1) {
  return window['go']['main']['App']['SetSoundCloudClientID'](arg1);
}

export function SetSpotifyCredentials(arg1, arg2) {
  return window['go']['main']['App']['SetSpotifyCredentials'](arg1, arg2);
}

export function SetYandexToken(arg1) {
  return window['go']['main']['App']['SetYandexToken'](arg1);
}

export function SetYouTubeAPIKey(arg1) {
  return window['go']['main']['App']['SetYouTubeAPIKey'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function SoundCloudClientIDSet() {
  return window['go']['main']['App']['SoundCloudClientIDSet']();
}

export function SpotifyConnected() {
  return window['go']['main']['App']['SpotifyConnected']();
}

export function StartMobileServer(arg1) {
  return window['go']['main']['App']['StartMobileServer'](arg1);
}

export function StartSpotifyLogin() {
  return window['go']['main']['App']['StartSpotifyLogin']();
}

export function StartYandexLogin() {
  return window['go']['main']['App']['StartYandexLogin']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function UpdatePlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePlaylist'](arg1, arg2, arg3);
}

export function UseWailsRuntime() {
  return window['go']['main']['App']['UseWailsRuntime']();
}

export function ValidateSource(arg1) {
  return window['go']['main']['App']['ValidateSource'](arg1);
}

export function YandexTokenConnected() {
  return window['go']['main']['App']['YandexTokenConnected']();
}

export function YouTubeAPIKeySet() {
  return window['go']['main']['App']['YouTubeAPIKeySet']();
}
